# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xiwei Cheng(程曦苇)
title: Undergraduate, Renmin Unniversity of China
email: xiw_c@ruc.edu.cn

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  laviaf

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | 
  I am a junior undergraduate student in [School of Statistics](http://stat.ruc.edu.cn), Renmin Unniversity of China, major in data science and minor in finance. 
  Since August 2021, I served as a research intern at the Language and Mental Intelligence Lab, Renmin University of China, supervised by Prof. [Ruihua Song](https://gsai.ruc.edu.cn/addons/teacher/index/info.html?ruccode=20200031) and Ph.D Candidate [Yuchong Sun](https://github.com/ycsun1972). 
  The vision-and-language and representation learning and AI for finance interest me greatly and can inspire my passion and creativity.
  
  I have the most experience working with <mark>Pthon</mark>, <mark>R</mark>, <mark>C++</mark>, <mark>SQL</mark>, <mark>Linux</mark>.

content:
  - title: Experience
    layout: list
    content:
      - title: Research Intern
        sub_title: Language and Mental Intelligence Lab, [Gaoling School of Artificial Intelligence](http://ai.ruc.edu.cn/), RUC
        caption: August 2021 - Present
        description: |
          It’s my honor to be guided by Prof. Ruihua Song and Ph.D Candidate Yuchong Sun, I learned a lot here. 
          Our lab mainly focus on cultivating AI with feeling and warmth. 
          My research mainly focus on vision and language.
      - title: Undergraduate Student
        sub_title: [School of Statistics](http://stat.ruc.edu.cn), RUC
        caption: September 2019 - Present
        description: |
          It’s glad to have the chance studying in such a open and vibrant school. 
          She taught me to be a person with romance, passion, and responsibility and have my foot on the ground.

  - title: Drafts
    layout: list
    content:
      - layout: left
        border: weak
        sub_title: Multi-Modal vs. Text Pre-trained Models——How Different They are in Embedding Text
        caption: September 2021 - Present
        description: |
          This research conducted a detailed analysis of changes in text embedding brought by the vision to language pre-training. 
          We used k-nearest neighbor approach to make the text embeding space of WenLan and RoBERTa comparable, and analyzed semantic and relationship of words using labeled dataset like ConceptNet.
      - layout: left
        border: weak
        sub_title: Evaluation of Marketing Communication Based on Multi-modal Method.
        caption: November 2021 - Present
        description: |
          This article proposes an approach to provide quantitative evidence for Integrated Marketing Communication (IMC) and Brand Identity theory.
          By implementing web scraping techniques and machine-learning approaches, we investigated web data on a large scale with multi-modal method.
          We finetuned Bert, ResNet and CLIP to calculate cosine similarity between embeddings and used GNN to recognize interaction patterns between nodes. 

  - title: Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Discourse analysis of the vulnerable
        caption: March 2021 - March 2022
        quote: >
          Analyze discourse features and government trust for vulnerable groups, advising government on digital transformation.
        description: |
          The government is currently engaged in multi-dimensional reforms and innovations around digital transformation. 
          Modern social governance requires accurate identification of the interests and demands of the public, especially for the vulnerable. 
          The vulnerable are often highly sensitive to public policy, their interests are easily infringed upon and ignored. They may also lack appropriate ways to express their demands under the traditional governance system. 
          We are interested in whether new online platforms for communication such as leadership message boards, can ameliorate the plight of the vulnerable.
          
          In this project, we collected all 2 million messages from the “Message Board for Leaders” from the past 10 years using the web crawler, then finetuned Bert with focal loss to classify the context of vulnerable groups and used text analysis to explore characteristics of the discourse.
          Our main findings are that affective and juridical expressions are significantly more often used by the vulnerable, and the affective and juridical expressions trend toward declining over time.
      - layout: top-middle
        title: RUCtronic
        additional_links:
          - title: laviaf/RUCtronic-based-on-vue-django-mysql
            icon: fab fa-github
            url: https://github.com/laviaf/RUCtronic-based-on-vue-django-mysql
        caption: October 2021 - December 2021
        quote: >
          a demo of B2C shopping platform, based on vue+django+mysql.
        description: |
          This is a course project collaborated with LLMllm2000. 
          We aimed to design and implement an online B2C shopping system like JD Mall or Amazon. 
          In this project, we finished user requirement analysis, database design, data generation, graphical user interface design, database security testing, complex sql queries and extreme testing.

  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      My personality is made up of two parts: romantic and rational. 
      I love all God's algorithms just like I love music. 
      I have been a symphony orchestra member for six years and have played the flute for 13 years. 
      Whenever I find that life needs a little more fun, I just go to a concert or sit on the lawn and sing.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
